name: "{{#if eq(ENV, 'beta')}}{{ LABEL}} (beta){{else}}{{LABEL}}{{/if}}"
packageKey: "{{#if eq(ENV, 'beta')}}{{PKG_KEY}}-beta{{else}}{{PKG_KEY}}{{/if}}""
description: "This driver extends the basic zwave functionality to include additional vendor specific parameters"
vendorSupportInformation: >-
   'This driver require a documented device to work properly.<br /><br />
    <a href="{{ COMMUNITY_LINK }}">SmartThings Community discussion</a><br /><br />
    <a href="{{ GITHUB }}/blob/main/README.md">GitHub Repository</a>'
permissions:
  zwave: {}
